version: '3'

services:
  postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: tranceanddance
      POSTGRES_PASSWORD: Transie123!
      POSTGRES_DB: postgresql
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: tranceanddance123@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Transie123!
    ports:
      - 5050:80
    depends_on:
      - postgresql
    
  backend:
    image: nestjs/cli
    restart: always
    build:
      context: ./backend
      dockerfile: dockerfile